# Generated by Django 3.1.4 on 2021-04-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210108_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulararaba',
            options={'verbose_name_plural': '7. Bula Raraba'},
        ),
        migrations.AlterModelOptions(
            name='lewenilotu',
            options={'verbose_name_plural': '1. Lewenilotu'},
        ),
        migrations.AlterModelOptions(
            name='matasiga',
            options={'verbose_name_plural': '2. Matasiga'},
        ),
        migrations.AlterModelOptions(
            name='valenilotu',
            options={'verbose_name_plural': '4. Valenilotu'},
        ),
        migrations.AlterModelOptions(
            name='veitokani',
            options={'verbose_name_plural': '3. Veitokani'},
        ),
        migrations.AlterModelOptions(
            name='veitosoyaki',
            options={'verbose_name_plural': '5. Veitosoyaki'},
        ),
        migrations.AlterModelOptions(
            name='veivakalotutaki',
            options={'verbose_name_plural': '6. Veivakalotutaki'},
        ),
    ]
